# Generated by Django 2.1.4 on 2019-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190327_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='disguised_image',
            field=models.FileField(default='images/missing.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
